services:
  cigarcertifierapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:5000;https://+:5001"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "LindVallsKaffe09!"
      SA_PASSWORD: "LindvallsKaffe09!"
      JWT_SECRET: "ckSUYIDVUbUBo2RNkmLVfg3YXvPETTmDLWzj30u4lkk="
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=CigarCertifierDB;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"

    ports:
      - "5000:5000"
      - "5001:5001"

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/https:ro

    depends_on:
      - sqlserver
    networks:
      - app-network
